openapi:
  specification_url: /api/swagger/v1/todo.yaml

# web server options
http:
  cors_enabled: false
  port: 8080
  response_timeout: 1.0

# application specific options
application:
  debug: false
  log_format: tty
  log_level: info

# options to control generation process
generation:
  default_min_float: -1.073741823e+09
  default_max_float: 1.073741823e+09
  default_min_int: 0
  default_max_int: 2147483647
  null_probability: 0.5
  suppress_errors: false
  use_examples: 'exclusively'